accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('register/', views.register, name='register'), # Przekierowanie na stronę rejestracji
    path('login/', views.signin, name='login'), # Przekierowanie na stronę logowania
    path('logout/', views.signout, name='logout'), # Przekierowanie na stronę wylogowania
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'), # Przekierowanie na stronę główną w przypadku wejścia na stronę
    path('dashboard/', views.dashboard, name='dashboard'), # Przekierowanie na pulpit
    path('dashboard/budget/', views.budget, name='budget'), # Przekierowanie na budżet
    path('about/', views.about, name='about'), # Przekierowanie na stronę o nas
    path('contact/', views.contact, name='contact'), # Przekierowanie na stronę kontaktową
    path('dashboard/calculator/', views.calculator, name='calculator'), # Przekierowanie na stronę kalkulatora
    path('dashboard/affordability/', views.affordability, name='affordability'), # Przekierowanie na stronę Przystępnościomierza
]

plusanto/urls.py
import debug_toolbar
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include('accounts.urls'), name='accounts'), # Przekierowanie na aplikację kont
    path('', include('main.urls'), name='index'), # Przekierowanie na stronę główną
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError


# Formularz dla rejestracji
class RegistrationForm(forms.Form):
    username = forms.CharField(label='Nazwa użytkownika', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Wprowadź nazwę użytkownika'}))
    first_name = forms.CharField(label='Imię', required=False, max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Wprowadź swoje imię'}))
    last_name = forms.CharField(label='Nazwisko', required=False, max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Wprowadź swoje nazwisko'}))
    email = forms.EmailField(label='Adres email', max_length=60, widget=forms.EmailInput(attrs={'placeholder': 'Wprowadź swój adres e-mail'}))
    password = forms.CharField(label='Hasło', widget=forms.PasswordInput(attrs={'placeholder': 'Wprowadź hasło'}))
    password_confirm = forms.CharField(label='Potwierdź hasło', widget=forms.PasswordInput(attrs={'placeholder': 'Wprowadź ponownie hasło'}))
    
    # Formy walidacji danych które przepuszczamy przez formularz
    
    def clean_username(self): # Walidacja długości nazwy użytkownika
        username = self.cleaned_data['username']
        if len(username) < 3:
            raise ValidationError('Nazwa użytkownika musi mieć co najmniej 3 znaki')
        return username
    
    def clean_password(self): # Walidacja hasła poprzez wbudowane moduły django
        password = self.cleaned_data.get('password')
        try:
            validate_password(password)
        except ValidationError as e:
            raise ValidationError(e.messages[0])
        return password

    def clean_password_confirm(self): # Walidacja identyczności haseł
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password != password_confirm:
            raise ValidationError('Hasła nie są identyczne')
        return password, password_confirm


# Formularz dla logowania
class SignInForm(forms.Form):
    username = forms.CharField(label='Nazwa użytkownika', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Wprowadź nazwę użytkownika'}))
    password = forms.CharField(label='Hasło', widget=forms.PasswordInput(attrs={'placeholder': 'Wprowadź hasło'}))

accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import RegistrationForm, SignInForm

def register(request): # Funkcja rejestracji użytkownika
    if request.method == 'POST': # Sprawdzamy czy użytkownik przesyła dane
        form = RegistrationForm(request.POST)
        if form.is_valid():  # Sprawdzamy czy formularz jest poprawny zgodnie z walidacją
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            try: # Sprawdzamy czy użytkownik znajduje się w bazie danych
                existing_user = User.objects.get(username=username)
                if existing_user:
                    messages.info(request, 'Użytkownik o podanej nazwie już istnieje')
                    return render(request, 'register.html', {'form': RegistrationForm(request.POST)})
            except User.DoesNotExist: # Jeżeli użytkownik nie istnieje w bazie danych możemy przejść dalej
                pass
            
            try: # Sprawdzamy czy adres email istnieje w bazie danych
                existing_email = User.objects.get(email=email)
                if existing_email: # Jeżeli email istnieje w bazie danych powracamy do formularza
                    messages.info(request, 'Podany adres email został już powiązany z innym użytkownikiem')
                    return render(request, 'register.html', {'form': RegistrationForm(request.POST)})
            except  User.DoesNotExist: # Jeżeli email nie istnieje w bazie danych możemy przejść dalej
                pass
            
            User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password) # Tworzymy użytkownika w bazie danych
            messages.success(request, "Rejestracja powiodła się!")
            # Logujemy użytkownika
            user = authenticate(request, username=username, password=password) 
            login(request, user)
            return redirect('index')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form}) # Jeżeli użytkownik nie wysyła żadnych danych to wyświetli formularz rejestracyjny

def signin(request): # Funkcja logowania  użytkownika
    if request.method == 'POST': # Sprawdzamy czy użytkownik przesyła dane
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)  # Sprawdzamy czy użytkownik istnieje w bazie danych
            if user is not None: #  Jeżeli użytkownik istnieje logujemy go
                login(request, user)
                messages.success(request, "Zalogowano pomyślnie!")
                next_url = request.GET.get('next')
                if next_url: # Jeżeli dostajemy specjalne przekierowanie, to przekierowujemy
                    return redirect(next_url)
                else:
                    return redirect('index')
            else:  # Jeżeli użytkownik nie istnieje wyświetlamy komunikat
                messages.error(request, "Błędne dane logowania!")
    else:
        form = SignInForm()
    return render(request, 'signin.html', {'form': form})

def signout(request): # Funkcja wylogowania użytkownika
    if request.user.is_authenticated: # Tylko jeżeli użytkownik jest zalogowany
        logout(request)
        messages.success(request, "Wylogowano pomyślnie!")
    return redirect('index')

accounts/templates/register.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    
    <title>Rejestracja</title>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>

<body>
    <header class="czarny-naglowek">
        <h1>Rejestracja</h1>
    </header>
    <h3><a href="{% url 'index' %}"class="button1">Wróć na stronę główną</a></h3>
    
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %} <!-- Zawsze przywołuj csrf_token gdy formularz korzysta z POST aby chronić przed CSRF (https://owasp.org/www-community/attacks/csrf#overview) <p> -->
        <label class="label_tekst" for="id_username">Nazwa użytkownika</label><br>
            {{form.username}}
            {{form.username.errors}}
        <br><br>
        <label class="label_tekst" for="id_first_name">Imię</label><br>
            {{form.first_name}}
            {{form.first_name.errors}}
        <br><br>
        <label class="label_tekst" for="id_last_name">Nazwisko</label><br>
            {{form.last_name}}
            {{form.last_name.errors}}
        <br><br>
        <label class="label_tekst" for="id_email">Email</label><br>
            {{form.email}}
            {{form.email.errors}}
        <br><br>
        <label class="label_tekst" for="id_password">Hasło</label><br>
            {{form.password}}
            {{form.password.errors}}
        <br><br>
        <label class="label_tekst" for="id_password_confirm">Potwierdź hasło</label><br>
            {{form.password_confirm}}
            {{form.password_confirm.errors}}
        <br><br>

        
        <button class="button2">Zarejestruj się</button>
    </form>
    <br>
    <a href="{% url 'login' %}" class="link"><u><b> Masz już konto? Zaloguj się.</u></b></a>
</body>
</html>

accounts/templates/signin.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Logowanie</title>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
    <header class="czarny-naglowek">
        <h1>Logowanie</h1>
    </header>
    <h3><a href="{% url 'index' %}"class="button1">Wróć na stronę główną</a></h3>
    
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label class="label_tekst" for="id_username">Nazwa użytkownika</label><br>
            {{form.username}}
            {{form.username.errors}}
        <br><br>
        <label class="label_tekst" for="id_password">Hasło</label><br>
            {{form.password}}
            {{form.password.errors}}
        <br><br>
        <div class="container">
        <button class="button2">Logowanie</button>
    </form>
    <br>
    <a href="{% url 'register' %}" class="link"><u><b>Nie masz jeszcze konta? Zarejestruj się.</u></b></a>
</body>
</html>