main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'), # Przekierowanie na stronę główną w przypadku wejścia na stronę
    path('dashboard/', views.dashboard, name='dashboard'), # Przekierowanie na pulpit
    path('dashboard/budget/', views.budget, name='budget'), # Przekierowanie na budżet
    path('about/', views.about, name='about'), # Przekierowanie na stronę o nas
    path('contact/', views.contact, name='contact'), # Przekierowanie na stronę kontaktową
    path('dashboard/calculator/', views.calculator, name='calculator'), # Przekierowanie na stronę kalkulatora
    path('dashboard/affordability/', views.affordability, name='affordability'), # Przekierowanie na stronę Przystępnościomierza
]

plusanto/urls.py
import debug_toolbar
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include('accounts.urls'), name='accounts'), # Przekierowanie na aplikację kont
    path('', include('main.urls'), name='index'), # Przekierowanie na stronę główną
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Budget_input_informations(models.Model): # Model bazy danych wejściowych budżetu użytkownika
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True)
    balance = models.IntegerField( min("0"))
    income = models.IntegerField( min("0"))
    expenses = models.IntegerField( min("0"))
    debt = models.IntegerField( min("0"))
    emergencyFund = models.IntegerField( min("0"))
    
class Budget_output_informations(models.Model): # Model bazy danych wyjściowych budżetu użytkownika
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True)
    balance = models.IntegerField( min("0"))
    budgetExpenses = models.IntegerField( min("0"))
    budgetWants = models.IntegerField( min("0"))
    allowance = models.IntegerField( min("0"))
    budgetEmergency = models.IntegerField( min("0"))
    debt = models.IntegerField( min("0"))

main/forms.py
from django import forms
from django.core.validators import MaxLengthValidator, integer_validator



# Formularz dla budżetu
class Budget_form(forms.Form):
    balance = forms.IntegerField(
        label="Saldo konta",
        min_value=0,
        max_value=999999999,
        required=True,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź saldo konta'})
    )
    income = forms.IntegerField(
        label="Dochód",
        min_value=0,
        max_value=999999999,
        required=True,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź dochód'})
    )
    expenses = forms.IntegerField(
        label="Wydatki stałe",
        min_value=0,
        max_value=999999999,
        required=True,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź wydatki stałe'})
    )
    debt = forms.IntegerField(
        label="Dług",
        min_value=0,
        max_value=999999999,
        required=True,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź dług'})
    )
    emergencyFund = forms.IntegerField(
        label="Fundusz awaryjny",
        min_value=0,
        max_value=999999999,
        required=True,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź fundusz awaryjny'})
    )
    plannedEmergencyFund = forms.IntegerField(
        label="Planowany fundusz awaryjny",
        min_value=0,
        max_value=999999999,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź planowany fundusz awaryjny'})
    )
    bufor = forms.IntegerField(
        label="Bufor",
        min_value=0,
        max_value=999999999,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź bufor'})
    )
    budgetType = forms.ChoiceField(
        label="Typ budżetu",
        choices=[('1', 'Stabilny: 50% wydatki / 30% zachcianki / 15% dodatek / 5% awaryjne'), 
                ('2', 'Rozwojowy: 50% wydatki / 30% dodatek / 20% awaryjne')],
        required=True,
        widget=forms.Select(attrs={'placeholder': 'Wybierz typ budżetu'})
    )
    
    percentExpenses = forms.IntegerField(
        label="Procent przekazywany na wydatki",
        min_value=0,
        max_value=50,
        required=False,
        disabled=True,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź procent wydatków'}),
        initial='50'
    )
    percentWants = forms.IntegerField(
        label="Procent przekazywany na zachcianki",
        min_value=0,
        max_value=50,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź procent zachcianek'}),
        initial='30'
    )
    percentAllowance = forms.IntegerField(
        label="Procent przekazywany na dodatek",
        min_value=0,
        max_value=50,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź procent dodatku'}),
        initial='15'
    )
    percentEmergency = forms.IntegerField(
        label="Procent przekazywany na awaryjność",
        min_value=0,
        max_value=50,
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Wprowadź procent awaryjny'}),
        initial='5'
    )
    

# Formularz kalkulatora podatku
class CalculatorForm(forms.Form):
    income = forms.IntegerField(
    label="Przychód roczny",
    min_value=1,
    max_value=999999999,
    required=True,
    widget=forms.NumberInput(attrs={'placeholder': 'Wpisz swój przychód roczny'})
    )
    deductions = forms.IntegerField(
    label="Odliczenia od podatku",
    min_value=0,
    max_value=999999999,
    required=True,
    widget=forms.NumberInput(attrs={'placeholder': 'Wpisz łączną wartość odliczeń od podatku'})
    )
    

# Formularz dla przystępnościomierza
class AffordabilityForm(forms.Form):
    expense = forms.IntegerField(
    label="Wartość wydatku",
    min_value=1,
    max_value=999999999,
    required=True,
    widget=forms.NumberInput(attrs={'placeholder': 'Wpisz wartość wydatku'})
    )
    frequency = forms.ChoiceField(
        label="Powtarzalność",
        choices=[('1', 'Jednorazowo'), 
                ('2', 'Miesięcznie'),
                ('3', 'Rocznie')],
        required=True,
        widget=forms.Select(attrs={'placeholder': 'Wybierz Powtarzalność'})
    )

main/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from .forms import Budget_form, CalculatorForm, AffordabilityForm
from .models import Budget_input_informations, Budget_output_informations
from django.http import JsonResponse
from .algorithms import budgetRule, affordabilityRule
from json import dumps

def index(request): # Strona główna
    return render(request, 'index.html')

def dashboard(request): # Pulpit
    if  request.user.is_authenticated:
        return render(request, 'dashboard.html')
    else:
        messages.info(request, "Aby wejść do pulpitu musisz się najpierw zalogować.")
        return redirect(f"{settings.LOGIN_URL}?next={request.path}")
    
def budget(request): # Sekcja budżetu
    if request.method == 'POST': # Sprawdzamy czy użytkownik przesyła dane
        form = Budget_form(request.POST)
        if form.is_valid():  # Sprawdzamy czy formularz jest poprawny
            # Wyciągamy dodatkowe dane w AJAXie
            distributeConf = request.POST.get('distributeConf', 'false') == 'true'
            # Wyciągamy dane z formularza
            balance = form.cleaned_data['balance']
            income = form.cleaned_data['income']
            expenses = form.cleaned_data['expenses']
            debt = form.cleaned_data['debt'] or 0
            emergencyFund = form.cleaned_data['emergencyFund'] or 0
            budgetType = form.cleaned_data['budgetType']
            bufor = form.cleaned_data['bufor'] or 0
            percentWants = form.cleaned_data['percentWants'] or 0
            percentAllowance = form.cleaned_data['percentAllowance'] or 0
            percentEmergency = form.cleaned_data['percentEmergency'] or 0
            plannedEmergencyFund = form.cleaned_data['plannedEmergencyFund'] or 0
            
            try:
                Budget_input_informations.objects.get(pk=request.user) # Sprawdzamy czy użytkownik ma już informacje
                Budget_input_informations.objects.filter(pk=request.user).update(balance=balance, income=income, expenses=expenses, debt=debt, emergencyFund=emergencyFund) # Aktualizujemy rekordy
            except Budget_input_informations.DoesNotExist: # Jeżeli użytkownik pierwszy raz wprowadza informacje, wpisujemy go do bazy danych jak nowego
                budget = Budget_input_informations.objects.create(user=request.user, balance=balance, income=income, expenses=expenses, debt=debt, emergencyFund=emergencyFund) # Tworzymy rekordy
                budget.save()
            
            balance, budgetExpenses, budgetWants, allowance, budgetEmergency, debt, messagesArray, lackingFunds = budgetRule(
                balance, income, expenses, debt, emergencyFund, budgetType, bufor, percentWants, percentAllowance, percentEmergency, plannedEmergencyFund, distributeConf)
            
            if lackingFunds:
                return JsonResponse({'status': 'error', 'message': 'Brak wystarczających środków.'})
            
            labels = ['Budżet wydatkowy', 'Dodatek', 'Budżet awaryjny']
            values = [budgetExpenses, allowance, budgetEmergency]
            if budgetType == '1':
                labels.insert(1, 'Budżet zachcianek')
                values.insert(1, budgetWants)
            
            # Zwróć odpowiedź dla strony o udanym zapisie danych oraz wartości dla pól budżetu
            response = JsonResponse({
                'status': 'success', 
                'message': 'Dane zostały zapisane.',
                'balance': int(balance),
                'budgetExpenses': int(budgetExpenses),
                'budgetWants': int(budgetWants),
                'allowance': int(allowance),
                'budgetEmergency': int(budgetEmergency),
                'debt': int(debt),
                'messages': messagesArray,
                'labels': labels,
                'values': values,
                }) 
            
            try:
                Budget_output_informations.objects.get(pk=request.user) # Sprawdzamy czy użytkownik ma już informacje
                Budget_output_informations.objects.filter(pk=request.user).update(balance=balance, budgetExpenses=budgetExpenses, budgetWants=budgetWants, allowance=allowance, budgetEmergency=budgetEmergency, debt=debt) # Aktualizujemy rekordy
            except Budget_output_informations.DoesNotExist: # Jeżeli użytkownik pierwszy raz wprowadza informacje, wpisujemy go do bazy danych jak nowego
                budget = Budget_output_informations.objects.create(user=request.user, balance=balance, budgetExpenses=budgetExpenses, budgetWants=budgetWants, allowance=allowance, budgetEmergency=budgetEmergency, debt=debt) # Tworzymy rekordy
                budget.save()
            
            
            # Deklarujemy ciasteczka z pozostałych wartości które warto zapisać
            response.set_cookie(key='budgetType', value=str(budgetType), max_age=60*60*24*365)
            response.set_cookie(key='bufor', value=str(bufor), max_age=60*60*24*365)
            response.set_cookie(key='percentWants', value=str(percentWants), max_age=60*60*24*365)
            response.set_cookie(key='percentAllowance', value=str(percentAllowance), max_age=60*60*24*365)
            response.set_cookie(key='percentEmergency', value=str(percentEmergency), max_age=60*60*24*365)
            response.set_cookie(key='plannedEmergencyFund', value=str(plannedEmergencyFund), max_age=60*60*24*365)
            return response
        else:
            # Zwróć odpowiedź dla strony o niepoprawnym formularzu
            return JsonResponse({'status': 'error', 'message': 'Niepoprawny format danych.'})
    else:
        try: # Sprawdzamy czy użytkownik posiada informacje, jeżeli tak wyświetlamy je jako wartości formularza
            budget = Budget_input_informations.objects.get(user=request.user)
            budgetType = request.COOKIES.get('budgetType', '1')
            bufor = request.COOKIES.get('bufor', '')
            percentWants = request.COOKIES.get('percentWants', '30')
            percentAllowance = request.COOKIES.get('percentAllowance', '15')
            percentEmergency = request.COOKIES.get('percentEmergency', '5')
            plannedEmergencyFund = request.COOKIES.get('plannedEmergencyFund', '')

            # Ustalamy wartości początkowe na te wcześniej zapisane
            form = Budget_form(initial={
                'balance': budget.balance,
                'income': budget.income,
                'expenses': budget.expenses,
                'debt': budget.debt,
                'emergencyFund': budget.emergencyFund,
                'budgetType': budgetType,
                'bufor': bufor,
                'percentWants': percentWants,
                'percentAllowance': percentAllowance,
                'percentEmergency': percentEmergency,
                'plannedEmergencyFund': plannedEmergencyFund,
            })
        except Budget_input_informations.DoesNotExist:
            form = Budget_form()
        
        try: # Sprawdzamy czy użytkownika posiada informacje wyjściowe, jeżeli tak to dajemy do JSONa
            budget = Budget_output_informations.objects.get(pk=request.user)
            
            labels = ['Budżet wydatkowy', 'Dodatek', 'Budżet awaryjny']
            values = [budget.budgetExpenses, budget.allowance, budget.budgetEmergency]
            if budgetType == '1':
                labels.insert(1, 'Budżet zachcianek')
                values.insert(1, budget.budgetWants)
            
            data = {
                'balance': budget.balance,
                'budgetExpenses': budget.budgetExpenses,
                'budgetWants': budget.budgetWants,
                'allowance': budget.allowance,
                'budgetEmergency': budget.budgetEmergency,
                'debt': budget.debt,
                'labels': labels,
                'values': values,
            }
            dataJSON = dumps(data)
        except Budget_output_informations.DoesNotExist:
            dataJSON = False
            
    return render(request, 'budget.html', {'form': form, 'dataJSON': dataJSON}) # Jeżeli użytkownik nie wysyła żadnych danych to wyświetli stronę informacji

def about(request): # O nas
    return render(request, 'about.html')

def contact(request): # Kontakt
    return render(request, 'contact.html')

def calculator(request): # Kalkulator
    form = CalculatorForm()
    return render(request, 'calculator.html', {'form': form})

def affordability(request): # Przystępnościomierz
    if request.method == 'POST': # Sprawdzamy czy użytkownik przesyła dane
        form = AffordabilityForm(request.POST)
        action = request.POST.get('action')
        if form.is_valid() and action == 'calculate':  # Sprawdzamy czy formularz jest poprawny
            # Wyciągamy dane z formularza
            expense = form.cleaned_data['expense']
            frequency = form.cleaned_data['frequency']
            
            budgetType = request.COOKIES.get('budgetType', '1')
            
            budget_in = Budget_input_informations.objects.get(user=request.user)
            income = budget_in.income
            budget_out = Budget_output_informations.objects.get(user=request.user)
            balance = budget_out.balance
            budgetExpenses = budget_out.budgetExpenses
            budgetWants = budget_out.budgetWants
            allowance = budget_out.allowance
            
            balanceAft, budgetExpensesAft, budgetWantsAft, allowanceAft, canDo, messagesArray, labels, values = affordabilityRule(income, balance, budgetExpenses, budgetWants, allowance, expense, frequency, budgetType)
            
            # Zwróć odpowiedź dla strony o udanym zapisie danych oraz wartości dla strony
            response = JsonResponse({
                'status': 'success', 
                'message': 'Obliczenia wykonane poprawnie.',
                'balance': int(balance),
                'budgetExpenses': int(budgetExpenses),

main/templates/about.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>O Plusanto</title>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
    <header class="czarny-naglowek">
    <h1>O Plusanto</h1>
    </header>
    <div class="about-div">
    <h3><a href="{% url 'index' %}"class="button1">Wróć na stronę główną</a></h3>
    <h2>Plusanto powstało celem projektu obrony praktyk. Projekt został utworzony przez dwóch uczniów Zespołu Szkół Elektroniczno-Telekomunikacyjnych w Lesznie na kierunku informatycznym.</h2>
    <h2>Zamysłem Plusanto było stworzenie strony internetowej do zarządzania finansami. Stworzyliśmy więc stronę zajmującą się ogólno pojętym zarządzaniem budżetu.</h2>
    <h2>Strona posiada własny algorytm stworzony na podstawie wielu filarów zarządzania budżetem. Algorytm umożliwia użytkownikowi kontrolę nad wieloma parametrami, a następnie algorytm zaleca przedsięwzięcia.</h2>

    <h2>Dziękujemy osobom które przyczyniły się wsparciem, opinią bądź testowaniem.</h2> 
    <h2>Szczególne podziękowania dla: Patryk Indziński, Kacper "Th3Kacper" Chmielewski</h2>
</div>
</body>
</html>

main/templates/affordability.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Przystępnościomierz</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script type="module" src="{% static 'js/affordability.js' %}" defer></script>
</head>
<body>
    <header class="czarny-naglowek">
        <h1>Przystępnościomierz</h1>
    </header>
    <h3><a href="{% url 'dashboard' %}"class="button1">Wróć do pulpitu</a></h3>
    <p>Oblicz czy możesz udźwignąć swój wydatek</p>
    
    <div id="responseMessage"></div>
    <form id="affordability-checker" method='POST'>
        {% csrf_token %}
        <br><br><label for="id_expense">Wartość wydatku</label>
            {{form.expense}}
            {{form.expense.errors}}
        <br><br><label for="id_frequency">Powtarzalność</label>
            {{form.frequency}}
            {{form.frequency.errors}}
        <br><br><button class="button2" data-action='calculate'>Oblicz przystępność</button>
    </form>
    <span id="errorValidateJS" style="color: red; display: none;"></span>

    <div id="calculatedResults" style="display:none">
        <h2>Wyliczenie przystępności</h2>
        <h2><p><span id="canDoDisplay"></span></p></h2>
        <div style='display:none'> {% comment %} Nie usuwać, ukryte ale potrzebne! {% endcomment %}
        <h2><p>Saldo przed: <span id="balanceDisplay"></span></p></h2>
        <h2><p>Saldo po: <span id="balanceAftDisplay"></span></p></h2>
        <h2><p>Budżet wydatkowy przed: <span id="budgetExpensesDisplay"></span></p></h2>
        <h2><p>Budżet wydatkowy po: <span id="budgetExpensesAftDisplay"></span></p></h2>
        <h2><p>Budżet zachcianek przed: <span id="budgetWantsDisplay"></span></p></h2>
        <h2><p>Budżet zachcianek po: <span id="budgetWantsAftDisplay"></span></p></h2>
        <h2><p>Dodatek przed: <span id="allowanceDisplay"></span></p></h2>
        <h2><p>Dodatek po: <span id="allowanceAftDisplay"></span></p></h2>
        </div>
        <button class="button2" data-action='save'>Zaktualizuj budżet wliczając ten wydatek</button>
        <ul id="messages"></ul>
        <span style="display: flex; justify-content: center; align-items: center; height: 70vh;">
            <canvas id="chartDisplay" width='600' height='600'></canvas>
        </span>
    </div>
</body>
</html>

main/templates/budget.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Budżet</title>
    <script type="module" src="{% static 'js/budget.js' %}" defer></script>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
    <header class="czarny-naglowek">
        <h1>Witaj w budżecie</h1>
    </header>
<h3><a href="{% url 'dashboard' %}" class="button1">Wróć do pulpitu</a></h3>

    <form id="budgetForm" method="post">
        {% csrf_token %}
        <br><br><label for="id_balance">Saldo konta</label>
            {{form.balance}}
            {{form.balance.errors}}

        <br><br><label for="id_income">Dochód</label>
            {{form.income}}
            {{form.income.errors}}

        <br><br><button disabled class="button3" title="Stałe, regularne wydatki, takie jak rachunki za prąd, wodę czy czynsz.">? </button>
        <label for="id_expenses">Wydatki stałe</label>
            {{form.expenses}}
            {{form.expenses.errors}}
        <br> <br>
        <span>
            <label for="debtCheckbox">Dług</label>
            <input type="checkbox" id="debtCheckbox" name="debtCheckbox">
        </span>
        <span id="debtSpan">
        <br><br><label for="id_debt">Dług</label>
            {{form.debt}}
            {{form.debt.errors}}
        </span>
        <br><br>
        <span>
        <button disabled class="button3" title="Twój fundusz awaryjny to środki przeznaczone na niespodziewane wydatki. Mogą one być potrzebne w sytuacjach, które wymagają większej ilości pieniędzy, niż aktualnie posiadasz w swoim budżecie.
        Planowany fundusz awaryjny to twój planowany fundusz w razie nagłej potrzeby. Rekomenduje się jego wysokość na poziomie co najmniej pięciokrotności miesięcznego dochodu.">?</button>
        <label for="emergencyFundCheckbox">Fundusz awaryjny</label>
            <input type="checkbox" id="emergencyFundCheckbox" name="emergencyFundCheckbox">
        </span>
        <span id="emergencyFundSpan">
        <br><br>
        
        <label for="id_emergencyFund">Fundusz awaryjny</label>
            {{form.emergencyFund}}
            {{form.emergencyFund.errors}}

        <br><br>
        
        <label for="id_plannedEmergencyFund">Planowany fundusz awaryjny</label>
            {{form.plannedEmergencyFund}}
            {{form.plannedEmergencyFund.errors}}
        </span>
        <span id="buforSpan">
            <br><br>
            <button disabled class="button3"  title="Dodatkowa kwota uwzględniana w budżecie, służy jako zabezpieczenie przed małymi, nagłymi wydatkami.">?</button>
            <label for="id_bufor">Bufor</label>
                {{form.bufor}}
                {{form.bufor.errors}}
        </span>

        <br><br>
        <button disabled class="button3" title="Budżet Stabilny Łączy oszczędzanie z uwzględnieniem codziennych potrzeb i przyjemności. Unikatowe dla budżetu stabilnego:
- Zachcianki,
- Przekazywanie dodatku do budżetu awaryjnego (jeżeli poniżej 40% planowanego funduszu).
Budżet Rozwojowy nakłada na ciągłe powiększanie kapitału oraz zabezpieczeń finansowych. Unikalne dla budżetu rozwojowego:
- Bufor do wydatków.">?</button>
        <label for="id_budgetType">Typ budżetu</label>
            {{form.budgetType}}
            {{form.budgetType.errors}}

        <br><br><label for="id_percentExpenses">Procent przekazywany na wydatki</label>
            {{form.percentExpenses}}
            {{form.percentExpenses.errors}}

        <span id="percentWantsSpan">
            <br><br><label for="id_percentWants">Procent przekazywany na zachcianki</label>
                {{form.percentWants}}
                {{form.percentWants.errors}}
        </span>

        <br><br><label for="id_percentAllowance">Procent przekazywany na dodatek</label>
            {{form.percentAllowance}}
            {{form.percentAllowance.errors}}

        <span id="percentEmergencySpan">
        <br><br><label for="id_percentEmergency">Procent przekazywany na awaryjność</label>
            {{form.percentEmergency}}
            {{form.percentEmergency.errors}}
        </span>
        <br><br><button class="button2" id='submitButton'>Zapisz</button>
    </form>
    <span id="errorValidateJS" style="color: red; display: none;"></span>
    <div id="responseMessage"></div>

{% if dataJSON %}
    <script type="module">
        import { budgetOutDataDisplay } from "{% static 'js/budget.js' %}";
        document.addEventListener('DOMContentLoaded', function() {
            const data = JSON.parse('{{ dataJSON|escapejs }}'); // Wyciąganie z JSONa danych o ostatnich danych wyjścia
            budgetOutDataDisplay(data);
        });
    </script>
{% endif %}
    <div id="calculatedResults" style="display:none">
        <h2>Wyliczony budżet</h2>
        <h2><p>Saldo: <span id="balanceDisplay"></span></p></h2>
        <div style='display:none'> {% comment %} Nie usuwać, ukryte ale potrzebne! {% endcomment %}
        <h2><p>Budżet wydatkowy: <span id="budgetExpensesDisplay"></span></p></h2>
        <h2><p>Budżet zachcianek: <span id="budgetWantsDisplay"></span></p></h2>
        <h2><p>Dodatek: <span id="allowanceDisplay"></span></p></h2>
        <h2><p>Budżet awaryjny: <span id="budgetEmergencyDisplay"></span></p></h2>
        </div>
        <h2 id='debtDisplayHeader'><p>Dług: <span id="debtDisplay"></span></p></h2>
        <ul id="messages" style="border: 10px solid black; display: none;"></ul>
        <br><br><br><br><br>
        <span style="display: flex; justify-content: center; align-items: center; height: 70vh;">
            <canvas id="chartDisplay" width='600' height='600'></canvas>
        </span>
    </div>
</body>
</html>

main/templates/calculator.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Kalkulator Podatków</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/calculator.js' %}" defer></script>
</head>
<body>
    <header class="czarny-naglowek">
        <h1>Kalkulator Podatków</h1>
    </header>
    <h3><a href="{% url 'dashboard' %}"class="button1">Wróć do pulpitu</a></h3>
    <p>Oblicz swój podatek w kilku prostych krokach.</p>

    <form id="tax-calculator" method='POST'>
        <br><br><label for="id_income">Przychód roczny</label>
            {{form.income}}
            {{form.income.errors}}
        <br><br><label for="id_deductions">Odliczenia od podatku</label>
            {{form.deductions}}
            {{form.deductions.errors}}
        <br><br>
        <button class="button2" type="submit">Oblicz podatek</button>
    </form>
    <span id="errorValidateJS" style="color: red; display: none;"></span>

    <div id="result" style="display:none;">
        <h2>Wynik:</h2>
        <p id="tax-amount"></p>
    </div>
</body>
</html>

main/templates/contact.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kontakt - Plusanto</title>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
    <header class="czarny-naglowek">
        <h1>Kontakt</h1>
    </header>
    <h3><a href="{% url 'index' %}"class="button1">Wróć na stronę główną</a></h3>
    <strong><p>Aby skontaktować się w sprawie strony, prosimy o kontakt mailowy na adres:</p></strong>
    <strong><p><a href="mailto:plusantoadmin@gmail.com">plusantoadmin@gmail.com</a></strong></p>
    <br /> <br />
    <strong><p>Kontakt do twórców</p></strong>
    <p>Bartosz Jędrzychowski</p>
    <p><a href="mailto:bartosz.jedrzychowski2006@gmail.com">bartosz.jedrzychowski2006@gmail.com</a></p>
    <br />

    <p>Maksymilian Antoniak</p>
    <p><a href="mailto:maksymilianantoniak2006@gmail.com">maksymilianantoniak2006@gmail.com</a></p>
</body>
</html>